name: shopping
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  cloud_firestore: ^3.4.4
  firebase_storage: ^10.3.5
  http: ^0.13.5
  awesome_notifications: ^0.6.21
  flutter_spinkit: ^5.1.0
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  circular_bottom_navigation: ^2.1.0
  focused_menu: ^1.0.5
  animated_splash_screen: ^1.3.0
  firebase_database: ^9.1.1
  email_validator: ^2.1.17
  flutter_pw_validator: ^1.4.2
  file_picker: ^5.0.1
  flutter_rating_bar: ^4.0.1
  mailer: ^5.2.0
  flutter_email_sender: ^5.1.0
  share: ^2.0.4
  min_id: ^1.1.0
  connectivity_plus: ^2.3.6+1
  card_swiper: ^2.0.4
  cached_network_image: ^3.2.2
  cryptography: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - Images/SplashScreen/
    - Images/Local/